# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mark/projects/ProjectMath

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mark/projects/ProjectMath

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mark/projects/ProjectMath/CMakeFiles /home/mark/projects/ProjectMath/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mark/projects/ProjectMath/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named projectmath

# Build rule for target.
projectmath: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 projectmath
.PHONY : projectmath

# fast build rule for target.
projectmath/fast:
	$(MAKE) -f CMakeFiles/projectmath.dir/build.make CMakeFiles/projectmath.dir/build
.PHONY : projectmath/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/projectmath.dir/build.make CMakeFiles/projectmath.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/projectmath.dir/build.make CMakeFiles/projectmath.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/projectmath.dir/build.make CMakeFiles/projectmath.dir/main.cpp.s
.PHONY : main.cpp.s

src/algebra.o: src/algebra.cpp.o
.PHONY : src/algebra.o

# target to build an object file
src/algebra.cpp.o:
	$(MAKE) -f CMakeFiles/projectmath.dir/build.make CMakeFiles/projectmath.dir/src/algebra.cpp.o
.PHONY : src/algebra.cpp.o

src/algebra.i: src/algebra.cpp.i
.PHONY : src/algebra.i

# target to preprocess a source file
src/algebra.cpp.i:
	$(MAKE) -f CMakeFiles/projectmath.dir/build.make CMakeFiles/projectmath.dir/src/algebra.cpp.i
.PHONY : src/algebra.cpp.i

src/algebra.s: src/algebra.cpp.s
.PHONY : src/algebra.s

# target to generate assembly for a file
src/algebra.cpp.s:
	$(MAKE) -f CMakeFiles/projectmath.dir/build.make CMakeFiles/projectmath.dir/src/algebra.cpp.s
.PHONY : src/algebra.cpp.s

src/geometry.o: src/geometry.cpp.o
.PHONY : src/geometry.o

# target to build an object file
src/geometry.cpp.o:
	$(MAKE) -f CMakeFiles/projectmath.dir/build.make CMakeFiles/projectmath.dir/src/geometry.cpp.o
.PHONY : src/geometry.cpp.o

src/geometry.i: src/geometry.cpp.i
.PHONY : src/geometry.i

# target to preprocess a source file
src/geometry.cpp.i:
	$(MAKE) -f CMakeFiles/projectmath.dir/build.make CMakeFiles/projectmath.dir/src/geometry.cpp.i
.PHONY : src/geometry.cpp.i

src/geometry.s: src/geometry.cpp.s
.PHONY : src/geometry.s

# target to generate assembly for a file
src/geometry.cpp.s:
	$(MAKE) -f CMakeFiles/projectmath.dir/build.make CMakeFiles/projectmath.dir/src/geometry.cpp.s
.PHONY : src/geometry.cpp.s

src/helloworld.o: src/helloworld.cpp.o
.PHONY : src/helloworld.o

# target to build an object file
src/helloworld.cpp.o:
	$(MAKE) -f CMakeFiles/projectmath.dir/build.make CMakeFiles/projectmath.dir/src/helloworld.cpp.o
.PHONY : src/helloworld.cpp.o

src/helloworld.i: src/helloworld.cpp.i
.PHONY : src/helloworld.i

# target to preprocess a source file
src/helloworld.cpp.i:
	$(MAKE) -f CMakeFiles/projectmath.dir/build.make CMakeFiles/projectmath.dir/src/helloworld.cpp.i
.PHONY : src/helloworld.cpp.i

src/helloworld.s: src/helloworld.cpp.s
.PHONY : src/helloworld.s

# target to generate assembly for a file
src/helloworld.cpp.s:
	$(MAKE) -f CMakeFiles/projectmath.dir/build.make CMakeFiles/projectmath.dir/src/helloworld.cpp.s
.PHONY : src/helloworld.cpp.s

src/menuSystem.o: src/menuSystem.cpp.o
.PHONY : src/menuSystem.o

# target to build an object file
src/menuSystem.cpp.o:
	$(MAKE) -f CMakeFiles/projectmath.dir/build.make CMakeFiles/projectmath.dir/src/menuSystem.cpp.o
.PHONY : src/menuSystem.cpp.o

src/menuSystem.i: src/menuSystem.cpp.i
.PHONY : src/menuSystem.i

# target to preprocess a source file
src/menuSystem.cpp.i:
	$(MAKE) -f CMakeFiles/projectmath.dir/build.make CMakeFiles/projectmath.dir/src/menuSystem.cpp.i
.PHONY : src/menuSystem.cpp.i

src/menuSystem.s: src/menuSystem.cpp.s
.PHONY : src/menuSystem.s

# target to generate assembly for a file
src/menuSystem.cpp.s:
	$(MAKE) -f CMakeFiles/projectmath.dir/build.make CMakeFiles/projectmath.dir/src/menuSystem.cpp.s
.PHONY : src/menuSystem.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... projectmath"
	@echo "... rebuild_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/algebra.o"
	@echo "... src/algebra.i"
	@echo "... src/algebra.s"
	@echo "... src/geometry.o"
	@echo "... src/geometry.i"
	@echo "... src/geometry.s"
	@echo "... src/helloworld.o"
	@echo "... src/helloworld.i"
	@echo "... src/helloworld.s"
	@echo "... src/menuSystem.o"
	@echo "... src/menuSystem.i"
	@echo "... src/menuSystem.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

